
### Get all articles
GET http://localhost:3000/articles

### Get articles by Id
GET http://localhost:3000/articles/48

### Get articles by Id
GET http://localhost:3000/articles?skip=0&take=2

### Add new article
POST http://localhost:3000/articles
content-type: application/json

{
  "title": "Test",
  "content": "This as an article content",
  "published": true,
  "UserId" : 45,
  "image" : "1.png"
}

### Delete an article
DELETE http://localhost:3000/articles/2
Accept: application/json


### Update an article
PATCH  http://localhost:3000/articles
content-type: application/json

{
  "id" : 3,
  "title": "Test2"
}

### GET articles number
GET http://localhost:3000/articles?number



